"use client";

import { ArrowLeft, ExternalLink } from "lucide-react";
import { formatDate, formatCurrency } from "@/lib/format";
import { statusLabel, statusTone } from "@/lib/labels";
import type { Course, Enrollment, Payment } from "@/types/academy";
import { Badge, Card, EmptyState, ProgressBar, SectionHeading, Skeleton } from "./ui";

type Props = { courses: Course[]; enrollments: Enrollment[]; payments: Payment[]; loading: boolean; selectedId: string | null; onSelect: (id: string | null) => void };

export function Courses({ courses, enrollments, payments, loading, selectedId, onSelect }: Props) {
  const selected = courses.find((course) => course.id === selectedId);
  const enrollment = enrollments.find((item) => item.courseId === selectedId);
  const payment = payments.find((item) => item.courseTitle === selected?.title || item.enrollmentId === enrollment?.id);
  if (loading) return <><SectionHeading title="My courses" /><div className="grid gap-4 md:grid-cols-2">{[1, 2, 3].map((item) => <Skeleton key={item} />)}</div></>;
  if (selected && enrollment) return <div><button onClick={() => onSelect(null)} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-blue-300"><ArrowLeft size={16} /> All courses</button><SectionHeading title={selected.title ?? enrollment.courseTitle ?? "Course details"} /><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Card><p className="text-slate-300">{selected.description ?? "Course details are being prepared."}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Instructor</p><p className="font-bold text-white">{selected.instructor ?? "Academy faculty"}</p></div><div><p className="text-xs text-slate-400">Duration</p><p className="font-bold text-white">{selected.durationWeeks ?? "—"} weeks</p></div><div><p className="text-xs text-slate-400">Schedule</p><p className="font-bold text-white">{selected.schedule ?? "Flexible"}</p></div></div><h3 className="mt-7 font-black text-white">Modules</h3><div className="mt-3 space-y-2">{(selected.modules ?? []).map((module, index) => <div key={module} className="flex items-center gap-3 rounded-xl bg-white/[0.04] p-3 text-sm text-slate-200"><span className={`grid h-6 w-6 place-items-center rounded-full text-xs font-bold ${(index + 1) <= Math.floor((enrollment.progressPercent ?? 0) / 100 * (selected.modules?.length ?? 1)) ? "bg-emerald-400 text-slate-950" : "bg-white/10 text-slate-400"}`}>{index + 1}</span>{module}</div>)}</div><h3 className="mt-7 font-black text-white">Learning resources</h3><div className="mt-3 grid gap-2">{(selected.resources ?? []).map((resource) => <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl bg-white/[0.04] p-3 text-sm font-bold text-blue-300">{resource.title ?? "Resource"}<ExternalLink size={15} /></a>)}</div></Card><Card><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Enrollment</p><p className="mt-2 text-xl font-black text-white">{statusLabel(enrollment.status)}</p><p className="mt-2 text-sm text-slate-400">Enrolled {formatDate(enrollment.enrolledAt)}</p><div className="mt-6"><div className="flex justify-between text-sm"><span className="text-slate-400">Progress</span><strong className="text-white">{enrollment.progressPercent ?? 0}%</strong></div><ProgressBar value={enrollment.progressPercent} /></div><p className="mt-6 text-xs font-bold uppercase tracking-widest text-slate-400">Payment</p><p className="mt-2 text-lg font-black text-white">{payment ? `${statusLabel(payment.status)} · ${formatCurrency(payment.amount)}` : "No payment record"}</p></Card></div></div>;
  return <div><SectionHeading title="My courses" detail="Track your learning progress and enrolled programs." />{!enrollments.length ? <EmptyState title="No courses enrolled" /> : <div className="grid gap-5 md:grid-cols-2">{enrollments.map((item) => { const course = courses.find((candidate) => candidate.id === item.courseId); return <Card key={item.id} className="cursor-pointer transition hover:border-blue-400/40" ><button onClick={() => item.courseId && onSelect(item.courseId)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">{course?.category ?? "Academy program"}</p><h3 className="mt-2 text-xl font-black text-white">{course?.title ?? item.courseTitle ?? "Course"}</h3></div><Badge tone={statusTone(item.certificateStatus)}>{statusLabel(item.certificateStatus)}</Badge></div><p className="mt-2 text-sm text-slate-400">{course?.instructor ?? "Academy faculty"}</p><div className="mt-5 flex justify-between text-sm"><span className="text-slate-400">Progress</span><strong className="text-white">{item.progressPercent ?? 0}%</strong></div><ProgressBar value={item.progressPercent} /><p className="mt-4 text-sm text-slate-300">Attendance: {item.attendedClasses ?? 0}/{item.totalClasses ?? 0}</p></button></Card>; })}</div>}</div>;
}
